### ISSUE TITLE
Barre de vie

### ISSUE THREAD

**Issue by waqiim** [Hyruki/The_Darkness_Lord#1]
Pourquoi Newen tu te compliques la vie ? Genre tu peux pas faire une barre de vie avec une variable à 100 et chaque dégât baisse de 2 ou 3 ?

**Comment by NewenRG** [comment]
j'ai fait une barre de vie avec les pourcentage pour que ça fonctionne avec une santé max variable que l'on pourra boost ou diminuer avec les effets de l'équipement et j'ai fait un truc giga long parce que je suis trop con mais t'inquiète elle fonctionne au moins XD

**Comment by waqiim** [comment]
T'inquiète de toute façon faudra que je fasse la connectivité dans un comit
